title: "Dillon Bowes"
author: "Dillon Bowes"
description: "Portfolio and Blog"
theme: slate
plugins:
  - jekyll-remote-theme

# Navigation bar
nav:
  - name: "Home"
    link: /
  - name: "Projects"
    link: /projects
  - name: "Blog"
    link: /blog
  - name: "Resume"
    link: /resume
