title: "Dillon Bowes"
author: "Dillon Bowes"
description: "Portfolio | Resume | Blog"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Enable dark mode styling
color_scheme: dark
